language: java
jdk:
 - oraclejdk8
language: ruby
rvm:
- 2.4.1
cache:
 - bundler
before_install:
 - bundle install
script:
 - bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)




